name: Docs

on:
  push:
    branches:
      - rename/aicspylibczi
    tags:
      - 'docs'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Depenencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Generate Docs
        env:
          BUILD_DOCS: true
        run: |
          mkdir cmake_build_debug
          cd cmake_build_debug
          cmake ..
          cmake --build . --target docs
          cd docs/html
          pwd
        shell: bash
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: rename/aicspylibczi
          BRANCH: gh-pages
          FOLDER: cmake_build_debug/docs/html
